/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AskRouteImport } from './routes/ask'
import { Route as BeforeAfterRouteImport } from './routes/before-after'
import { Route as CheckAnswerRouteImport } from './routes/check-answer'
import { Route as ForensicsRouteImport } from './routes/forensics'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge-graph'
import { Route as NewVerificationRouteImport } from './routes/new-verification'
import { Route as ResearchPaperAuditorRouteImport } from './routes/research-paper-auditor'
import { Route as RiskHeatmapRouteImport } from './routes/risk-heatmap'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as AnswerIdRouteImport } from './routes/answer.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const BeforeAfterRoute = BeforeAfterRouteImport.update({
  id: '/before-after',
  path: '/before-after',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckAnswerRoute = CheckAnswerRouteImport.update({
  id: '/check-answer',
  path: '/check-answer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForensicsRoute = ForensicsRouteImport.update({
  id: '/forensics',
  path: '/forensics',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const NewVerificationRoute = NewVerificationRouteImport.update({
  id: '/new-verification',
  path: '/new-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchPaperAuditorRoute = ResearchPaperAuditorRouteImport.update({
  id: '/research-paper-auditor',
  path: '/research-paper-auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskHeatmapRoute = RiskHeatmapRouteImport.update({
  id: '/risk-heatmap',
  path: '/risk-heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerIdRoute = AnswerIdRouteImport.update({
  id: '/answer/$id',
  path: '/answer/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/before-after': typeof BeforeAfterRoute
  '/check-answer': typeof CheckAnswerRoute
  '/forensics': typeof ForensicsRoute
  '/history': typeof HistoryRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/new-verification': typeof NewVerificationRoute
  '/research-paper-auditor': typeof ResearchPaperAuditorRoute
  '/risk-heatmap': typeof RiskHeatmapRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/uploads': typeof UploadsRoute
  '/answer/$id': typeof AnswerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/before-after': typeof BeforeAfterRoute
  '/check-answer': typeof CheckAnswerRoute
  '/forensics': typeof ForensicsRoute
  '/history': typeof HistoryRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/new-verification': typeof NewVerificationRoute
  '/research-paper-auditor': typeof ResearchPaperAuditorRoute
  '/risk-heatmap': typeof RiskHeatmapRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/uploads': typeof UploadsRoute
  '/answer/$id': typeof AnswerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/before-after': typeof BeforeAfterRoute
  '/check-answer': typeof CheckAnswerRoute
  '/forensics': typeof ForensicsRoute
  '/history': typeof HistoryRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/new-verification': typeof NewVerificationRoute
  '/research-paper-auditor': typeof ResearchPaperAuditorRoute
  '/risk-heatmap': typeof RiskHeatmapRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/uploads': typeof UploadsRoute
  '/answer/$id': typeof AnswerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ask'
    | '/before-after'
    | '/check-answer'
    | '/forensics'
    | '/history'
    | '/knowledge-graph'
    | '/new-verification'
    | '/research-paper-auditor'
    | '/risk-heatmap'
    | '/settings'
    | '/sources'
    | '/uploads'
    | '/answer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask'
    | '/before-after'
    | '/check-answer'
    | '/forensics'
    | '/history'
    | '/knowledge-graph'
    | '/new-verification'
    | '/research-paper-auditor'
    | '/risk-heatmap'
    | '/settings'
    | '/sources'
    | '/uploads'
    | '/answer/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ask'
    | '/before-after'
    | '/check-answer'
    | '/forensics'
    | '/history'
    | '/knowledge-graph'
    | '/new-verification'
    | '/research-paper-auditor'
    | '/risk-heatmap'
    | '/settings'
    | '/sources'
    | '/uploads'
    | '/answer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AskRoute: typeof AskRoute
  BeforeAfterRoute: typeof BeforeAfterRoute
  CheckAnswerRoute: typeof CheckAnswerRoute
  ForensicsRoute: typeof ForensicsRoute
  HistoryRoute: typeof HistoryRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  NewVerificationRoute: typeof NewVerificationRoute
  ResearchPaperAuditorRoute: typeof ResearchPaperAuditorRoute
  RiskHeatmapRoute: typeof RiskHeatmapRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  UploadsRoute: typeof UploadsRoute
  AnswerIdRoute: typeof AnswerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/before-after': {
      id: '/before-after'
      path: '/before-after'
      fullPath: '/before-after'
      preLoaderRoute: typeof BeforeAfterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-answer': {
      id: '/check-answer'
      path: '/check-answer'
      fullPath: '/check-answer'
      preLoaderRoute: typeof CheckAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forensics': {
      id: '/forensics'
      path: '/forensics'
      fullPath: '/forensics'
      preLoaderRoute: typeof ForensicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-verification': {
      id: '/new-verification'
      path: '/new-verification'
      fullPath: '/new-verification'
      preLoaderRoute: typeof NewVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-paper-auditor': {
      id: '/research-paper-auditor'
      path: '/research-paper-auditor'
      fullPath: '/research-paper-auditor'
      preLoaderRoute: typeof ResearchPaperAuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-heatmap': {
      id: '/risk-heatmap'
      path: '/risk-heatmap'
      fullPath: '/risk-heatmap'
      preLoaderRoute: typeof RiskHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer/$id': {
      id: '/answer/$id'
      path: '/answer/$id'
      fullPath: '/answer/$id'
      preLoaderRoute: typeof AnswerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AskRoute: AskRoute,
  BeforeAfterRoute: BeforeAfterRoute,
  CheckAnswerRoute: CheckAnswerRoute,
  ForensicsRoute: ForensicsRoute,
  HistoryRoute: HistoryRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  NewVerificationRoute: NewVerificationRoute,
  ResearchPaperAuditorRoute: ResearchPaperAuditorRoute,
  RiskHeatmapRoute: RiskHeatmapRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  UploadsRoute: UploadsRoute,
  AnswerIdRoute: AnswerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
